config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'top#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :pictures do
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # >>>>>>ここから
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # =====ここまでを追記
    # 省略
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
    validates :content, presence: true
    belongs_to :picture
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable,:omniauthable
  mount_uploader :avatar, AvatarUploader #deviseの設定配下に追記
         
  has_many :pictures
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  
  def self.create_unique_string
    SecureRandom.uuid
  end
   
   
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)


  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  def index
    @pictures=Picture.all
    @users=User.all
  end

  def new
    @picture=Picture.new
  end

  def create
    upload_file = picture_params[:file]
    picture = {}
    if upload_file != nil 
      picture[:filename] = upload_file.original_filename
      picture[:file] = upload_file.read
    end
        picture[:user_id] = picture_params[:user_id]
    picture[:content] = picture_params[:content]
    @picture = Picture.new(picture)
    if @picture.save
      redirect_to pictures_path, notice: "投稿しました。"
    else
      flash[:error] = "保存できませんでした。"
      render 'new'
    end
  end

  def edit
    @picture=Picture.find(params[:id])
  end

  def update
    @picture=Picture.find(params[:id])
    upload_file = picture_params[:file]
    picture = {}
    if upload_file != nil 
      picture[:filename] = upload_file.original_filename
      picture[:file] = upload_file.read
    end 
    picture[:content] = picture_params[:content]
    @picture.update(picture)
    redirect_to pictures_path
  end

  def show
    # send_dataはバイナリファイルをブラウザに表示するため
    # http://railsdoc.com/references/send_data

    @picture = Picture.find(params[:id])
    send_data @picture.file, :type => 'image/jpeg', :disposition => 'inline'
  end

  def destroy
    @picture=Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path, notice:"画像を削除しました。"
  end
  
  private

    def picture_params
      params.require(:picture).permit(
        :filename,:file, :user_id, :content
      )   
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
        confirm_pictures_path
        elsif action_name == 'edit'
          picture_path
        end
    end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>

    <style type="text/css">
  body { padding-top: 80px; }
  body { padding-top: 80px; }
  @media ( min-width: 768px ) {
    #banner {
      min-height: 300px;
      border-bottom: none;
    }
    .bs-docs-section {
      margin-top: 8em;
    }
    .bs-component {
      position: relative;
    }
    .bs-component .modal {
      position: relative;
      top: auto;
      right: auto;
      left: auto;
      bottom: auto;
      z-index: 1;
      display: block;
    }
    .bs-component .modal-dialog {
      width: 90%;
    }
    .bs-component .popover {
      position: relative;
      display: inline-block;
      width: 220px;
      margin: 20px;
    }
    .nav-tabs {
      margin-bottom: 15px;
    }
    .progress {
      margin-bottom: 10px;
    }
  }
  </style>
    
</head>
<body>

<header>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a href="/"class="navbar-brand">Insta</a>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <li><%= link_to "画像一覧", pictures_path %></li>
          <li><%= link_to "画像投稿", new_picture_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'マイページ', edit_user_registration_path %></li>
              <li><%= link_to "ログアウト",destroy_user_session_path,method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン",new_user_session_path %></li>
              <li><%= link_to "サインアップ",new_user_registration_path %></li>
            <% end %> 
        </ul>
      </div>
    </div>
  </div>
</header>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/delete.html.erb
<h1>Pictures#delete</h1>
<p>Find me in app/views/pictures/delete.html.erb</p>

app/views/pictures/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="well bs-component">
                <fieldset>
                    <legend>投稿編集画面</legend>
                        <%= form_for(@picture, url: choose_new_or_edit) do |f| %>

                            <% if @picture.errors.any? %>
                                <div id="error_explanation">
                                    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
                                    <ul>
                                        <% @picture.errors.full_messages.each do |msg| %>
                                            <li><%= msg %></li>
                                        <% end %>
                                    </ul>
                                </div>
                            <% end %>
                            <%= image_tag picture_path(@picture), class: "middle-img" %>
                            <div class="form-group">
                                <%= f.file_field :file,accept: "image/jpeg"  %>
                                <%= f.hidden_field :user_id, :value => current_user.id%>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-10">
                                    <%= f.text_field :content , class: "form-control" , id: "textArea" , :placeholder => @picture.content %> 
                                </div>
                            </div>
                            <%= f.submit "アップロードする" ,class: "btn btn-primary" %>
                        <% end %>
                </fieldset>
            </div>
        </div>
    </div>
</div>

app/views/pictures/index.html.erb
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <div class="alert alert-dismissible alert-info">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h6><%= notice %></h6>
          </div>
    </div>
  </div>
  </div>
  
<div class="row">
  <div class="col-lg-12">
<% @pictures.each do |picture| %>

        <div class="bs-component">
          <blockquote>
            <% loginUserId=picture.user_id - 1 %>
  <h4>@<%= @users.find(picture.user_id).name %> さんの投稿</h4>
    <h6><%= picture.content %></h6>
    <%= image_tag picture_path(picture), class: "middle-img" %>
    <% if(current_user.id == picture.user_id) %>
      <%= link_to "編集",edit_picture_path(picture.id),class: "btn btn-info" %>
      <%= link_to "削除",picture_path(picture.id), method: :delete, data: {confirm: "本当に削除しますか？"},class: "btn btn-danger" %>
    <% end %>
    <br>
          </blockquote>

<% end %>
</div>
</div>
</div>

app/views/pictures/new.html.erb
    <div class="row">
        <div class="col-lg-6">
            <div class="well bs-component">
                <fieldset>
                    <legend>画像投稿画面</legend>
                        <%= form_for(@picture) do |f| %>
                        
                            <% if @picture.errors.any? %>
                                <div id="error_explanation">
                                    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
                                    <ul>
                                        <% @picture.errors.full_messages.each do |msg| %>
                                            <li><%= msg %></li>
                                        <% end %>
                                    </ul>
                                </div>
                            <% end %>
                            
                        <div class="form-group">
                            <%= f.file_field :file,accept: "image/jpeg" %>
                        </div>
                        <%= f.hidden_field :user_id, :value => current_user.id%>
                        <div class="form-group">
                            <div class="col-lg-10">
                                <%= f.text_field :content , class: "form-control" , id: "textArea" %> 
                            </div>
                        </div>
                        <%= f.submit "アップロードする" ,class: "btn btn-primary" %>
                        <% end %>
                </fieldset>
            </div>
        </div>
    </div>

app/views/pictures/show.html.erb
<h1>Pictures#show</h1>
<p>Find me in app/views/pictures/show.html.erb</p>
<%= image_tag show_image_image_path(@image), class: "large-img" %>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>

app/views/top/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <div class="alert alert-dismissible alert-info">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h6><%= notice %><%= alert %></h6>
          </div>
      </div>
  </div>
</div>

<div class="page-header" id="banner">
    <div class="row">
      <div class="col-lg-8 col-md-7 col-sm-6">
        <h1>Insta</h1>
        <p class="lead">Instagramやった事無いので、想像でそれっぽいの作りました。</p>
      </div>
    </div>
  </div>